function F = F_realified(in1,in2)
%F_REALIFIED
%    F = F_REALIFIED(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Oct-2021 20:26:00

X1 = in1(1,:);
X2 = in1(2,:);
Xprime1 = in1(3,:);
Xprime2 = in1(4,:);
cspeed = in1(5,:);
lamprime1 = in1(9,:);
lamprime2 = in1(10,:);
omega = in1(6,:);
para1 = in2(1,:);
para2 = in2(2,:);
para3 = in2(3,:);
v1 = in1(7,:);
v2 = in1(8,:);
vprime1 = in1(11,:);
vprime2 = in1(12,:);
F = [X2;X2.*cspeed+X1.*para1.*(X1-1.0);Xprime2;X2+Xprime2.*cspeed-Xprime1.*(para1-X1.*para1.*2.0);v1;cspeed.*v1+omega.*v2+para1.*(X1-1.0)+X1.*para1.*((para2.*sin(omega))./omega-(sin(omega.*para3).*(para2-1.0))./(omega.*para3));-omega+v2;cspeed.*v2-omega.*v1-X1.*para1.*((para2.*(cos(omega)-1.0))./omega+((cos(omega.*para3)-1.0).*(para2-1.0))./(omega.*para3));-lamprime1+vprime1+lamprime1.*v1-lamprime2.*v2;v1+lamprime1.*(para1.*(X1-1.0)+X1.*para1.*(-1.0./omega.^2.*para2.*(cos(omega)+omega.*sin(omega)-1.0)+(1.0./omega.^2.*cos(omega.*para3).*(cos(omega.*para3)-1.0).*(para2-1.0))./para3+(1.0./omega.^2.*sin(omega.*para3).*(sin(omega.*para3)-omega.*para3).*(para2-1.0))./para3))+cspeed.*vprime1-lamprime1.*v1+lamprime2.*v2+omega.*vprime2+cspeed.*lamprime1.*v1-cspeed.*lamprime2.*v2+Xprime1.*para1.*((para2.*sin(omega))./omega+omega.*para3.*sin(omega.*para3).*(para2-1.0)+1.0)+X1.*lamprime2.*para1.*(1.0./omega.^2.*para2.*(sin(omega)-omega.*cos(omega))+(1.0./omega.^2.*sin(omega.*para3).*(cos(omega.*para3)-1.0).*(para2-1.0))./para3-(1.0./omega.^2.*cos(omega.*para3).*(sin(omega.*para3)-omega.*para3).*(para2-1.0))./para3);-lamprime2+vprime2+lamprime1.*v2+lamprime2.*v1;v2+lamprime2.*(para1.*(X1-1.0)+X1.*para1.*(-1.0./omega.^2.*para2.*(cos(omega)+omega.*sin(omega)-1.0)+(1.0./omega.^2.*cos(omega.*para3).*(cos(omega.*para3)-1.0).*(para2-1.0))./para3+(1.0./omega.^2.*sin(omega.*para3).*(sin(omega.*para3)-omega.*para3).*(para2-1.0))./para3))+cspeed.*vprime2-lamprime1.*v2-lamprime2.*v1-omega.*vprime1-Xprime1.*para1.*((para2.*(cos(omega)-1.0))./omega-omega.*para3.*(cos(omega.*para3)-1.0).*(para2-1.0))+cspeed.*lamprime1.*v2+cspeed.*lamprime2.*v1-X1.*lamprime1.*para1.*(1.0./omega.^2.*para2.*(sin(omega)-omega.*cos(omega))+(1.0./omega.^2.*sin(omega.*para3).*(cos(omega.*para3)-1.0).*(para2-1.0))./para3-(1.0./omega.^2.*cos(omega.*para3).*(sin(omega.*para3)-omega.*para3).*(para2-1.0))./para3)];
