function concat_F = F_Hopf(in1,Re_FIXVAL,Im_FIXVAL,in4,TAU)
%F_HOPF
%    CONCAT_F = F_HOPF(IN1,RE_FIXVAL,IM_FIXVAL,IN4,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Oct-2021 20:40:15

PARA1 = in4(1,:);
PARA2 = in4(2,:);
X1 = in1(1,:);
X2 = in1(2,:);
X3 = in1(3,:);
X4 = in1(4,:);
X5 = in1(5,:);
X6 = in1(6,:);
X7 = in1(7,:);
X8 = in1(8,:);
X9 = in1(9,:);
X10 = in1(10,:);
X11 = in1(11,:);
X12 = in1(12,:);
concat_F = [exp(-X1)-PARA1.*X1-X1.*X5+X2.*X5;exp(-X2)-PARA2.*X2+X1.*X5-X2.*X5;Im_FIXVAL.*X6+X5.*X7-Re_FIXVAL.*(PARA1+X5)-Re_FIXVAL.*exp(-X1).*cos(TAU.*X6)-Im_FIXVAL.*exp(-X1).*sin(TAU.*X6);Re_FIXVAL.*X5+X6.*X8-X7.*(PARA2+X5)-X7.*exp(-X2).*cos(TAU.*X6)-X8.*exp(-X2).*sin(TAU.*X6);-Re_FIXVAL.*X6+X5.*X8-Im_FIXVAL.*(PARA1+X5)-Im_FIXVAL.*exp(-X1).*cos(TAU.*X6)+Re_FIXVAL.*exp(-X1).*sin(TAU.*X6);Im_FIXVAL.*X5-X6.*X7-X8.*(PARA2+X5)-X8.*exp(-X2).*cos(TAU.*X6)+X7.*exp(-X2).*sin(TAU.*X6);-Re_FIXVAL+X7+Im_FIXVAL.*X10-Re_FIXVAL.*X9+X5.*X11-cos(TAU.*X6).*(Im_FIXVAL.*TAU.*X10.*exp(-X1)-Re_FIXVAL.*TAU.*X9.*exp(-X1))+sin(TAU.*X6).*(Im_FIXVAL.*TAU.*X9.*exp(-X1)+Re_FIXVAL.*TAU.*X10.*exp(-X1))+Re_FIXVAL.*X3.*exp(-X1).*cos(TAU.*X6)+Im_FIXVAL.*X3.*exp(-X1).*sin(TAU.*X6);Re_FIXVAL-X7-X7.*X9-X6.*X11+X8.*X10+cos(TAU.*X6).*(TAU.*X7.*X9.*exp(-X2)-TAU.*X8.*X10.*exp(-X2))+sin(TAU.*X6).*(TAU.*X7.*X10.*exp(-X2)+TAU.*X8.*X9.*exp(-X2))-X11.*(PARA2+X5)-X11.*exp(-X2).*cos(TAU.*X6)-X12.*exp(-X2).*sin(TAU.*X6)+X4.*X7.*exp(-X2).*cos(TAU.*X6)+X4.*X8.*exp(-X2).*sin(TAU.*X6);-Im_FIXVAL+X8-Im_FIXVAL.*X9-Re_FIXVAL.*X10+X5.*X12+cos(TAU.*X6).*(Im_FIXVAL.*TAU.*X9.*exp(-X1)+Re_FIXVAL.*TAU.*X10.*exp(-X1))+sin(TAU.*X6).*(Im_FIXVAL.*TAU.*X10.*exp(-X1)-Re_FIXVAL.*TAU.*X9.*exp(-X1))+Im_FIXVAL.*X3.*exp(-X1).*cos(TAU.*X6)-Re_FIXVAL.*X3.*exp(-X1).*sin(TAU.*X6);Im_FIXVAL-X8-X7.*X10-X8.*X9-X6.*X12+cos(TAU.*X6).*(TAU.*X7.*X10.*exp(-X2)+TAU.*X8.*X9.*exp(-X2))-sin(TAU.*X6).*(TAU.*X7.*X9.*exp(-X2)-TAU.*X8.*X10.*exp(-X2))-X12.*(PARA2+X5)-X12.*exp(-X2).*cos(TAU.*X6)+X11.*exp(-X2).*sin(TAU.*X6)+X4.*X8.*exp(-X2).*cos(TAU.*X6)-X4.*X7.*exp(-X2).*sin(TAU.*X6);-X1+X2+X4.*X5-X3.*(PARA1+X5)-X3.*exp(-X1);X1-X2+X3.*X5-X4.*(PARA2+X5)-X4.*exp(-X2)];
