function Jacobian_tau = Jacobian_tau(in1,in2,X5,in4)
%JACOBIAN_TAU
%    JACOBIAN_TAU = JACOBIAN_TAU(IN1,IN2,X5,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Oct-2021 20:40:18

x_tau1 = in2(1,:);
x_tau2 = in2(2,:);
Jacobian_tau = reshape([-exp(-x_tau1),0.0,0.0,-exp(-x_tau2)],[2,2]);
