function Jacobian_0 = Jacobian_0(in1,in2,X5,in4)
%JACOBIAN_0
%    JACOBIAN_0 = JACOBIAN_0(IN1,IN2,X5,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Oct-2021 20:40:18

PARA1 = in4(1,:);
PARA2 = in4(2,:);
Jacobian_0 = reshape([-PARA1-X5,X5,X5,-PARA2-X5],[2,2]);
